### ISSUE TITLE
Installation instructions don't seem to work

### ISSUE THREAD

**Issue by tobymurray** [mlmitch/vandelay#1]
Following the installation instructions, I get the following:
`cp: cannot stat './vandelay.sh': No such file or directory`

It looks like the expected execution directory is outside the repository, but the `install.sh` script does a `cp ./vandelay.sh /usr/local/bin/vandelay` that expects to be in the root of the repository. Consider revising the instructions or updating the script to e.g. use a path relative to the script.

Workaround is to move to the root of the repository before running `sudo ./install.sh`.

**Comment by mlmitch** [comment]
https://github.com/mlmitch/vandelay/pull/2
